title: Alex Johnson # your name (or website title) here
logo: "/images/cutmypic (1).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Self-motivated developer with a passion in learning.
  <br>
  Programming Language: Java
  <br>
  Front End: HTML, CSS, Bootstrap, jQuery, JSON
  <br>
  Back End: Spring Framework, Spring MVC, Spring Boot, Spring Security, MySQL, Hibernate, Tomcat, REST, Redis
  <br>
  Other: Maven, SSL, Git, Github, Postman
  <br>
  [Back to Main Page](https://kj2386.github.io)
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-139291866-1 # your Google Analytics tracking ID here

